### PR TITLE
evaluate.py with updated function for type scoring

### PR DESCRIPTION
**Pull request by cainesap**
Previously type and token scores were always the same.

I've written a new function for type scoring which compares 2 lexicons (gold and test/hypothesis) and then calculates P/R/F scores.

Or have I misunderstood how type scoring works? (I found it hard to find a good definition online..)

### CODE REVIEW

**Comment by mmmaat** [comment]
Thanks Andrew, I discussed with @alecristia (wordseg project leader)... We had a working evaluation one time, that is now broken for some reason (I probably introduced a bug while refactoring). @elinlarsen maybe you have an idea as you wrote the evaluation.py this summer?

As we want to maintain stability of the results (for publication), I will try to resolve that issue from our internal codebase first. And then consider your implementation. And, bad news never come alone, I have hot topics to work on first (bugs in dibs, a new wordseg-syll for syllabification).

**Comment by cainesap** [comment]
Yes of course, this all makes sense; I look forward to hearing more

**Comment by mmmaat** [comment]
Hi Andrew, finally I'll merge your PR :+1: just with minor changes... I just wait for feedback from my team

**Comment by mmmaat** [comment]
Thank you Andrew, all is good and PR has been merged!

**Comment by cainesap** [comment]
That's great! Thanks for the update, and I'm pleased my PR was approved :)

**Pull request merged**
